(()=>{"use strict";
const S={catalog:null,lang:localStorage.getItem("launch-language")||"ar",history:[]};
const $=s=>document.querySelector(s),grid=$("#serviceGrid"),nav=$("#mainNav"),drawer=$("#drawer"),drawerContent=$("#drawerContent"),modal=$("#chatModal"),messages=$("#chatMessages"),input=$("#chatInput"),voice=$("#voiceButton"),language=$("#language");
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function boot(){const r=await fetch("/launch-v1/data/services.json",{cache:"no-store"});if(!r.ok)throw Error("catalog");S.catalog=await r.json();render();bindLayanButtons()}
function render(){nav.innerHTML=S.catalog.sections.map(x=>'<button type="button" data-section="'+x.id+'">'+x.icon+" "+esc(x.title)+"</button>").join("");renderCards(S.catalog.sections)}
function renderCards(list){grid.innerHTML=list.map(x=>'<article class="service-card"><div class="service-icon">'+x.icon+'</div><h3>'+esc(x.title)+'</h3><p>'+esc(x.desc)+'</p><button type="button" data-open="'+x.id+'">عرض التفاصيل ←</button></article>').join("")||"<p>ما لقينا خدمة مطابقة.</p>"}
function openService(id){const x=S.catalog.sections.find(v=>v.id===id);if(!x)return;drawerContent.innerHTML='<span class="eyebrow">SERVICE</span><h2>'+x.icon+" "+esc(x.title)+'</h2><p>'+esc(x.desc)+'</p><div class="detail-list">'+x.items.map(i=>'<button class="detail-item" type="button" data-detail="'+x.id+":"+i.id+'"><strong>'+esc(i.title)+'</strong><span>'+esc(i.desc)+'</span></button>').join("")+'</div>';drawer.setAttribute("aria-hidden","false")}
function openDetail(key){const [sid,iid]=key.split(":"),x=S.catalog.sections.find(v=>v.id===sid),i=x?.items.find(v=>v.id===iid);if(!i)return;drawerContent.innerHTML='<span class="eyebrow">SERVICE DETAIL</span><h2>'+esc(i.title)+'</h2><p>'+esc(i.desc)+'</p><div class="detail-box"><strong>الخدمة مرتبطة الآن بمسار ليان وCompany AI</strong><span>عند البدء، نرسل طلب الخدمة إلى مسار التخطيط المركزي ثم تتابع ليان معك التفاصيل. لا يوجد اعتماد على صفحة قديمة أو مسار قديم.</span></div><div class="detail-actions"><button class="primary" type="button" data-start="'+esc(i.title)+'">ابدأ هذه الخدمة مع ليان</button><button class="secondary" type="button" data-plan="'+esc(i.title)+'">حلّل طلبي أولاً</button></div>'}
function closeDrawer(){drawer.setAttribute("aria-hidden","true")}
function openChat(prefill=""){modal.setAttribute("aria-hidden","false");if(prefill)input.value=prefill;setTimeout(()=>input.focus(),60)}
function closeChat(){stopVoice();modal.setAttribute("aria-hidden","true")}
function add(text,role){const e=document.createElement("div");e.className="bubble "+role;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight}
function speak(text){if(!speechSynthesis)return;const u=new SpeechSynthesisUtterance(text);u.lang=S.lang==="ar"?"ar-SA":S.lang;u.rate=.96;speechSynthesis.cancel();speechSynthesis.speak(u)}
async function chat(text){add(text,"user");input.value="";const t=document.createElement("div");t.className="bubble assistant";t.textContent=S.lang==="ar"?"عم فكّر…":"Thinking…";messages.appendChild(t);try{const r=await fetch("/launch-api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,language:S.lang,history:S.history})});const d=await r.json();const reply=d.reply||"ليان ما قدرت تكمل الطلب حالياً.";t.textContent=reply;S.history.push({role:"user",content:text},{role:"assistant",content:reply});S.history=S.history.slice(-12);speak(reply)}catch(_){t.textContent="تعذر الاتصال بليان حالياً. لم يتم تنفيذ أي إجراء خارجي."}}
async function analyzeService(title){try{const r=await fetch("/launch-api/company/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:"أريد البدء بخدمة: "+title,language:S.lang,history:S.history})});const d=await r.json();add("الخدمة: "+title,"user");add("تم ربط الطلب بمسار Company AI المركزي. "+(d.summary||"ليان ستتابع معك التفاصيل."),"assistant")}catch(_){add("تعذر تحليل الخدمة حالياً، ولم يتم تنفيذ أي إجراء خارجي.","assistant")}}
let rec=null;function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add("المتصفح لا يدعم الاتصال الصوتي حالياً. يمكنك متابعة ليان بالدردشة النصية.","assistant");return}if(rec){stopVoice();return}rec=new SR();rec.lang=S.lang==="ar"?"ar-SA":S.lang;rec.interimResults=false;rec.continuous=false;voice.textContent="⏹️ إيقاف الاتصال الصوتي";rec.onresult=e=>{const t=e.results[0]?.[0]?.transcript?.trim();if(t)chat(t)};rec.onerror=()=>{stopVoice();add("لم يتم فتح الميكروفون. إذا طلب الهاتف إذن الميكروفون، اسمح به ثم اضغط زر الاتصال مرة ثانية.","assistant")};rec.onend=stopVoice;rec.start()}
function stopVoice(){if(rec){try{rec.stop()}catch(_){ }rec=null}if(voice)voice.textContent="🎙️ ابدأ الاتصال الصوتي مع ليان"}
function setLang(v){S.lang=v;document.documentElement.lang=v;document.documentElement.dir=v==="ar"?"rtl":"ltr";language.value=v;localStorage.setItem("launch-language",v)}
function bindLayanButtons(){const hv=$("#heroVoice");if(hv)hv.onclick=()=>{openChat();setTimeout(startVoice,120)};const tb=$("#textOnlyButton");if(tb)tb.onclick=()=>openChat()}
document.addEventListener("click",e=>{const sec=e.target.closest("[data-section]"),op=e.target.closest("[data-open]"),de=e.target.closest("[data-detail]"),cl=e.target.closest("[data-close]"),cc=e.target.closest("[data-close-chat]"),st=e.target.closest("[data-start]"),pl=e.target.closest("[data-plan]");if(sec)openService(sec.dataset.section);if(op)openService(op.dataset.open);if(de)openDetail(de.dataset.detail);if(cl)closeDrawer();if(cc)closeChat();if(st){const title=st.dataset.start;closeDrawer();openChat("أريد البدء بخدمة: "+title)}if(pl){const title=pl.dataset.plan;closeDrawer();openChat("أريد تحليل طلبي لخدمة: "+title);setTimeout(()=>analyzeService(title),100)}});
$("#browseServices").onclick=()=>$("#services").scrollIntoView({behavior:"smooth"});$("#heroChat").onclick=openChat;$("#openChat").onclick=openChat;voice.onclick=startVoice;
$("#serviceSearch").oninput=e=>{const q=e.target.value.trim().toLowerCase();renderCards(!q?S.catalog.sections:S.catalog.sections.filter(x=>(x.title+" "+x.desc+" "+x.items.map(i=>i.title+" "+i.desc).join(" ")).toLowerCase().includes(q)))};
$("#chatForm").onsubmit=e=>{e.preventDefault();const v=input.value.trim();if(v)chat(v)};language.onchange=e=>setLang(e.target.value);setLang(S.lang);
boot().catch(()=>grid.innerHTML="<p>تعذر تحميل كتالوج الخدمات الجديد.</p>");
})();