import {openAcademy} from "./academy.js";
let data={sections:[]};
const FALLBACK="en",SUPPORTED=["ar","en","es","fr","de","pt","it","tr","nl"],RTL=new Set(["ar","fa","ur","he"]);
const labels={ar:{layan:"تحدث مع ليان",search:"شو الخدمة اللي عم تدور عليها؟",hero:"شو بدك تبني أو تطوّر؟",heroSub:"Company AI تبني مواقع وتطبيقات وأنظمة ذكاء اصطناعي وحلول نمو للأعمال.",explore:"استكشف الخدمات",text:"دردشة نصية مع ليان",voice:"محادثة صوتية مع ليان",notSure:"مو متأكد شو تختار؟ اسأل ليان.",details:"عرض التفاصيل",start:"ابدأ الآن",back:"رجوع",online:"متصلة الآن",send:"إرسال",type:"اكتب رسالتك…"},en:{layan:"Talk to Layan",search:"What service are you looking for?",hero:"What do you want to build or improve?",heroSub:"Company AI builds websites, apps, AI systems and growth solutions for businesses.",explore:"Explore services",text:"Text chat with Layan",voice:"Voice chat with Layan",notSure:"Not sure what to choose? Ask Layan.",details:"View details",start:"Start now",back:"Back",online:"Online",send:"Send",type:"Type your message…"},es:{layan:"Hablar con Layan",search:"¿Qué servicio buscas?",hero:"¿Qué quieres crear o mejorar?",heroSub:"Company AI crea sitios web, aplicaciones, sistemas de IA y soluciones de crecimiento.",explore:"Explorar servicios",text:"Chat de texto con Layan",voice:"Chat de voz con Layan",notSure:"¿No sabes qué elegir? Pregunta a Layan.",details:"Ver detalles",start:"Empezar",back:"Volver",online:"En línea",send:"Enviar",type:"Escribe tu mensaje…"},fr:{layan:"Parler avec Layan",search:"Quel service recherchez-vous ?",hero:"Que voulez-vous créer ou améliorer ?",heroSub:"Company AI crée des sites, applications, systèmes IA et solutions de croissance.",explore:"Découvrir les services",text:"Chat texte avec Layan",voice:"Chat vocal avec Layan",notSure:"Vous ne savez pas quoi choisir ? Demandez à Layan.",details:"Voir les détails",start:"Commencer",back:"Retour",online:"En ligne",send:"Envoyer",type:"Écrivez votre message…"},de:{layan:"Mit Layan sprechen",search:"Welche Leistung suchen Sie?",hero:"Was möchten Sie bauen oder verbessern?",heroSub:"Company AI entwickelt Websites, Apps, KI-Systeme und Wachstumslösungen.",explore:"Leistungen entdecken",text:"Textchat mit Layan",voice:"Sprachchat mit Layan",notSure:"Unsicher? Fragen Sie Layan.",details:"Details ansehen",start:"Starten",back:"Zurück",online:"Online",send:"Senden",type:"Nachricht schreiben…"},pt:{layan:"Falar com Layan",search:"Que serviço procura?",hero:"O que você quer criar ou melhorar?",heroSub:"A Company AI cria sites, apps, sistemas de IA e soluções de crescimento.",explore:"Explorar serviços",text:"Chat de texto com Layan",voice:"Chat de voz com Layan",notSure:"Não sabe o que escolher? Pergunte à Layan.",details:"Ver detalhes",start:"Começar",back:"Voltar",online:"Online",send:"Enviar",type:"Digite sua mensagem…"}};
function detectLanguage(){for(const x of navigator.languages||[navigator.language]){const c=String(x||"").toLowerCase().split("-")[0];if(SUPPORTED.includes(c))return c}return FALLBACK}
function setDocumentLanguage(c){document.documentElement.lang=c;document.documentElement.dir=RTL.has(c)?"rtl":"ltr"}
function t(c,k){return labels[c]?.[k]||labels[FALLBACK][k]||k}
function supportedLanguages(){return SUPPORTED.slice()}
let lang=localStorage.getItem("company-ai-language")||detectLanguage();if(!SUPPORTED.includes(lang))lang="en";
const layanState={history:[]};
async function getLayanConfig(){const r=await fetch("/api/sales-agent/public/config",{cache:"no-store"});if(!r.ok)throw Error("Layan service unavailable");return r.json()}
async function chat(message,language){const c=await getLayanConfig();const r=await fetch("/api/sales-agent/"+c.build_id+"/conversation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,language,channel:"text",assistant:"layan",history:layanState.history.slice(-6)})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Layan service unavailable");const reply=String(d.reply||"").trim();layanState.history.push({role:"user",text:message},{role:"assistant",text:reply});return{reply,language:d.language||language}}
function resetChat(){layanState.history=[]}
function speak(text,language){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=language==="ar"?"ar-LB":language+"-"+(language==="en"?"US":language==="fr"?"FR":language==="de"?"DE":language==="es"?"ES":"");u.rate=.96;window.speechSynthesis.speak(u)}
async function startVoice(s,stateEl,sub,textEl,start){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){stateEl.textContent="Voice input is not supported in this browser.";sub.textContent="You can use text chat instead.";return}const rec=new SR();window.__layanRec=rec;rec.lang=lang==="ar"?"ar-LB":lang;rec.interimResults=false;rec.continuous=false;stateEl.textContent="Listening…";sub.textContent="Speak naturally.";start.disabled=true;let timer=null;rec.onresult=async e=>{clearTimeout(timer);const msg=e.results[0][0].transcript.trim();textEl.textContent=msg;stateEl.textContent="Layan is thinking…";try{const r=await chat(msg,lang);textEl.textContent=r.reply;stateEl.textContent="Layan is speaking…";speak(r.reply,lang);sub.textContent="You can speak again when she finishes."}catch(err){stateEl.textContent="Something went wrong.";sub.textContent=err.message}finally{start.disabled=false}};rec.onerror=e=>{clearTimeout(timer);stateEl.textContent="Voice input stopped.";sub.textContent=e.error||"Please try again.";start.disabled=false};rec.onend=()=>{clearTimeout(timer);if(start.disabled)start.disabled=false};rec.start();timer=setTimeout(()=>{try{rec.stop()}catch{}},15000)}
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const text=o=>typeof o==="string"?o:(o?.[lang]||o?.en||"");
const icons={web:"M4 6h16M4 12h16M4 18h16",apps:"M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2",ai:"M12 3v18M3 12h18M5.6 5.6l12.8 12.8M18.4 5.6 5.6 18.4",growth:"M4 18l5-6 4 3 7-9",commerce:"M4 5h16l-2 11H6L4 5M9 20h.01M17 20h.01",enterprise:"M5 20V7l7-4 7 4v13M9 20v-5h6v5"};
const icon=id=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+(icons[id]||icons.enterprise)+'"/></svg>';
function render(){
 setDocumentLanguage(lang);
 $("#app").innerHTML=`<header class="header"><div class="shell header-inner"><button class="brand" data-home><span class="brand-mark">CA</span><span class="brand-name">Company <span>AI</span></span></button><nav class="nav">${data.sections.map(s=>`<button data-section="${s.id}">${esc(text(s.title))}</button>`).join("")}<button data-academy>AI Academy</button><button data-chat>${esc(t(lang,"layan"))}</button></nav><select class="language" id="language">${supportedLanguages().map(x=>`<option value="${x}">${x==="ar"?"العربية":x==="en"?"English":x==="es"?"Español":x==="fr"?"Français":x==="de"?"Deutsch":x==="pt"?"Português":x.toUpperCase()}</option>`).join("")}</select></div></header><main><section class="hero layanHero"><div class="shell hero-grid"><div class="hero-copy"><div class="eyebrow">COMPANY AI</div><h1>${esc(t(lang,"hero"))}</h1><p class="hero-sub">${esc(t(lang,"heroSub"))}</p><div class="actions"><button class="btn primary" data-services>${esc(t(lang,"explore"))}</button><button class="btn secondary layanChoice" data-chat>${esc(t(lang,"text"))}</button><button class="btn secondary layanChoice voiceChoice" data-voice>${esc(t(lang,"voice"))}</button></div><form class="search" id="search"><input id="search-input" type="search" placeholder="${esc(t(lang,"search"))}" autocomplete="off"><button>${esc(t(lang,"explore"))}</button></form></div><div class="hero-visual"><img src="/assets/layan-office.webp?v=20260920-v3" alt="Layan in Company AI office" loading="eager" decoding="async" onerror="this.hidden=true;this.parentElement.classList.add('image-fallback')"><div class="hero-overlay"></div><div class="hero-caption"><span class="dot"></span> Layan • LIVE<small>${esc(t(lang,"online"))}</small></div></div></div></section><section class="service-section" id="services"><div class="shell"><div class="section-head"><div><div class="eyebrow">01</div><h2>${esc(t(lang,"services"))}</h2><p>${esc(t(lang,"heroSub"))}</p></div></div><div class="service-grid">${data.sections.map(s=>`<article class="service-card"><div class="service-mark">${icon(s.id)}</div><h3>${esc(text(s.title))}</h3><p>${esc(text(s.description))}</p><div class="card-foot"><span></span><button class="link-btn" data-section="${s.id}">${esc(t(lang,"details"))} →</button></div></article>`).join("")}</div></div></section><section class="shell chat-note"><div><strong>${esc(t(lang,"notSure"))}</strong><p>${esc(t(lang,"heroSub"))}</p></div><button class="btn primary" data-chat>${esc(t(lang,"layan"))}</button></section></main>`;
 $("#language").value=lang;bind();
}
function bind(){
 document.querySelectorAll("[data-home]").forEach(b=>b.onclick=()=>scrollTo({top:0,behavior:"smooth"}));
 document.querySelectorAll("[data-services]").forEach(b=>b.onclick=()=>$("#services").scrollIntoView({behavior:"smooth"}));
 document.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>openSection(b.dataset.section));
 document.querySelectorAll("[data-academy]").forEach(b=>b.onclick=()=>openAcademy());
 document.querySelectorAll("[data-chat]").forEach(b=>b.onclick=()=>openChat());
 document.querySelectorAll("[data-voice]").forEach(b=>b.onclick=()=>{try{openVoice()}catch(e){toast(e.message)}});
 $("#language").onchange=e=>{lang=e.target.value;localStorage.setItem("company-ai-language",lang);render()};
 $("#search").onsubmit=e=>{e.preventDefault();search($("#search-input").value)};
}
function search(q){const n=String(q||"").trim().toLowerCase();if(!n)return $("#services").scrollIntoView({behavior:"smooth"});for(const s of data.sections){if((text(s.title)+" "+text(s.description)).toLowerCase().includes(n))return openSection(s.id);for(const i of s.items)if((text(i.title)+" "+text(i.description)).toLowerCase().includes(n))return openSection(s.id,i.id)}openChat(q)}
function openSection(id,focus){
 const s=data.sections.find(x=>x.id===id),d=$("#drawer");if(!s)return;
 d.innerHTML=`<div class="drawer-panel"><div class="drawer-head"><div><div class="eyebrow">${esc(text(s.title))}</div><h2>${esc(text(s.title))}</h2><p>${esc(text(s.description))}</p></div><button class="close" data-close>×</button></div><div class="drawer-body"><div class="option-grid">${s.items.map(i=>`<button class="option" data-item="${i.id}"><h3>${esc(text(i.title))}</h3><p>${esc(text(i.description))}</p><b>${esc(t(lang,"start"))} →</b></button>`).join("")}</div></div></div>`;
 d.classList.add("open");d.querySelector("[data-close]").onclick=closeDrawer;d.onclick=e=>{if(e.target===d)closeDrawer()};d.querySelectorAll("[data-item]").forEach(b=>b.onclick=()=>openItem(s,b.dataset.item));if(focus)openItem(s,focus);
}
function openItem(s,id){const i=s.items.find(x=>x.id===id);if(!i)return;const body=$("#drawer .drawer-body");body.innerHTML=`<div class="crumb"><button data-back>← ${esc(t(lang,"back"))}</button><span>${esc(text(s.title))}</span><strong>${esc(text(i.title))}</strong></div><article class="detail"><div class="service-mark">${icon(s.id)}</div><h2>${esc(text(i.title))}</h2><p>${esc(text(i.description))}</p><div class="actions"><button class="btn primary" data-start>${esc(t(lang,"start"))}</button><button class="btn secondary" data-ask>${esc(t(lang,"text"))}</button></div></article>`;body.querySelector("[data-back]").onclick=()=>openSection(s.id);body.querySelector("[data-start]").onclick=()=>{closeDrawer();openChat(text(i.title))};body.querySelector("[data-ask]").onclick=()=>{closeDrawer();openChat(text(i.title))}}
function closeDrawer(){const d=$("#drawer");d.classList.remove("open");d.setAttribute("aria-hidden","true")}
function ensureVoiceStage(){
 const id="layanVoiceStage";
 let s=document.getElementById(id);
 if(s)return s;
 s=document.createElement("section");
 s.id=id;s.className="layanVoiceStage";s.setAttribute("aria-hidden","true");
 s.innerHTML=`<div class="layanVoicePanel">
   <div class="layanVoiceTop"><div><strong>Layan</strong><small>LIVE • Company AI</small></div><button class="close layanClose" aria-label="Close">×</button></div>
   <div class="layanVoiceVisual"><img class="layanOfficeDedicated" src="/assets/layan-office.webp?v=20260920-v4" alt="Layan in Company AI office" loading="eager" decoding="async"><div class="layanVoiceGlow"></div><div class="layanVoiceOfficeBadge"><span class="dot"></span> LIVE</div></div>
   <div class="layanVoiceState" id="layanVoiceState">Layan is ready…</div>
   <div class="layanVoiceSub" id="layanVoiceSub">Speak naturally in your language.</div>
   <div class="layanVoiceText" id="layanVoiceText"></div>
   <button id="layanStart" class="btn primary layanStart">Start conversation</button>
 </div>`;
 document.body.appendChild(s);
 return s;
}
function openVoice(){ensureVoiceStage();if(typeof window.startLayanVoice!=="function")throw Error("Voice module is not ready");return window.startLayanVoice();}
function openChat(prefill=""){const c=$("#chat");resetChat();c.innerHTML=`<div class="chat-panel"><div class="chat-head"><div class="layan-id"><span class="dot"></span><div><strong>Layan</strong><small>${esc(t(lang,"online"))}</small></div></div><button class="close" data-close>×</button></div><div class="chat-messages" id="messages"><div class="msg ai">${esc(t(lang,"notSure"))}</div></div><form class="chat-form"><input id="chat-input" placeholder="${esc(t(lang,"type"))}" value="${esc(prefill)}"><button>${esc(t(lang,"send"))}</button></form></div>`;c.classList.add("open");c.querySelector("[data-close]").onclick=closeChat;c.onclick=e=>{if(e.target===c)closeChat()};c.querySelector("form").onsubmit=async e=>{e.preventDefault();const x=$("#chat-input"),m=x.value.trim();if(!m)return;add(m,"user");x.value="";try{const r=await chat(m,lang);add(r.reply,"ai")}catch(err){add(err.message,"ai")}};c.querySelector("#chat-input").focus()}
function add(v,k){const m=$("#messages"),x=document.createElement("div");x.className="msg "+k;x.textContent=v;m.appendChild(x);m.scrollTop=m.scrollHeight}
function closeChat(){const c=$("#chat");c.classList.remove("open");c.setAttribute("aria-hidden","true")}
function toast(v){const x=document.createElement("div");x.className="toast";x.textContent=v;document.body.append(x);x.classList.add("show");setTimeout(()=>x.remove(),2800)}
addEventListener("keydown",e=>{if(e.key==="Escape"){closeDrawer();closeChat()}});
async function loadData(){
 try{
  const r=await fetch("/frontend-v2/data/services.json?v=20260920-v5",{cache:"no-store"});
  if(!r.ok)throw new Error("Service catalog unavailable");
  data=await r.json();
  render();
 }catch(e){
  document.querySelector("#app").innerHTML='<main style="min-height:100dvh;display:grid;place-items:center;padding:24px;font-family:system-ui;background:#f7fcff;color:#122640"><section style="max-width:620px;text-align:center;background:#fff;border:1px solid #dce9f1;border-radius:24px;padding:32px;box-shadow:0 20px 60px rgba(31,87,122,.1)"><div style="font-size:12px;font-weight:900;letter-spacing:.16em;color:#2b9dce">COMPANY AI</div><h1 style="margin:10px 0">Loading Company AI…</h1><p style="color:#64778c">Please refresh the page. If this message remains, the service catalog could not be loaded.</p></section></main>';
  console.error(e);
 }
}
loadData();